version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk

    steps:
      - checkout
      - run: gradle test
      - store_test_results:
          path: build/test-results/test